artifact_uri: file:///Volumes/partition/projects/learning/movieclassifier/stores/model/0/99331a090a42489cb5019ca1e23a0c41/artifacts
end_time: 1621563063462
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 99331a090a42489cb5019ca1e23a0c41
run_uuid: 99331a090a42489cb5019ca1e23a0c41
source_name: ''
source_type: 4
source_version: ''
start_time: 1621563063093
status: 3
tags: []
user_id: fallou
