artifact_uri: file:///Volumes/partition/projects/learning/movieclassifier/stores/model/1/219261a54f854ae5a1cb1a547f5a9cdb/artifacts
end_time: 1621657630635
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 219261a54f854ae5a1cb1a547f5a9cdb
run_uuid: 219261a54f854ae5a1cb1a547f5a9cdb
source_name: ''
source_type: 4
source_version: ''
start_time: 1621657630448
status: 3
tags: []
user_id: fallou
