artifact_uri: file:///Volumes/partition/projects/learning/movieclassifier/stores/model/0/f998f8814aa4466698b793d9a25e3d31/artifacts
end_time: 1621656944403
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f998f8814aa4466698b793d9a25e3d31
run_uuid: f998f8814aa4466698b793d9a25e3d31
source_name: ''
source_type: 4
source_version: ''
start_time: 1621656944103
status: 3
tags: []
user_id: fallou
