artifact_uri: file:///Volumes/partition/projects/learning/movieclassifier/stores/model/1/0781f73db3e3446ebd4fb15c02163c9b/artifacts
end_time: 1621657702880
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 0781f73db3e3446ebd4fb15c02163c9b
run_uuid: 0781f73db3e3446ebd4fb15c02163c9b
source_name: ''
source_type: 4
source_version: ''
start_time: 1621657702726
status: 3
tags: []
user_id: fallou
