artifact_uri: file:///Volumes/partition/projects/learning/movieclassifier/stores/model/0/40b0c3bc0b934cfa998e43bc5b9679d0/artifacts
end_time: 1621657325037
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 40b0c3bc0b934cfa998e43bc5b9679d0
run_uuid: 40b0c3bc0b934cfa998e43bc5b9679d0
source_name: ''
source_type: 4
source_version: ''
start_time: 1621657324888
status: 3
tags: []
user_id: fallou
