artifact_uri: file:///Volumes/partition/projects/learning/movieclassifier/stores/model/0/422daa1262a54380b54ccecd54a23726/artifacts
end_time: 1621657000410
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 422daa1262a54380b54ccecd54a23726
run_uuid: 422daa1262a54380b54ccecd54a23726
source_name: ''
source_type: 4
source_version: ''
start_time: 1621657000142
status: 3
tags: []
user_id: fallou
